/**
 * THE EXCHANGE'S WIRE FORMAT (bands.finance Play, 24 Sep). One contract for the browser (src/game/net.ts) and the
 * room server (game-server/, a Cloudflare Durable Object). JSON over one WebSocket per visitor.
 *
 * Safety by construction: no free text ever crosses the wire. A visitor's name is generated by the server, what
 * they say is one of PHRASES, what they do is one of EMOTES, and a leaderboard score is the server's own: an online
 * round is played on the server. The player lays a band ("lay"), the server deals a seed it never sends, runs
 * simulate() (src/game/lpGame.ts) and streams the result one tick at a time as its clock reaches each tick ("tick");
 * the player may "close" at any time, which settles the round at the last tick already sent. The browser never sees
 * the seed or any tick before its time, so there is nothing to search offline.
 */

/** the plaza is a disc of this radius, in world units (metres); the server clamps every position into it */
export const WORLD_RADIUS = 42;
/** a client sends at most this many moves a second; the server drops the excess */
export const MOVE_HZ = 12;
/** the server broadcasts positions this many times a second, batched */
export const TICK_HZ = 10;
/** the most visitors one room holds; the next one gets { t: "full" } */
export const ROOM_CAP = 60;
/** the fastest a walker may move, metres a second (sprint included), for the server's sanity check */
export const MAX_SPEED = 9;
/** an online round's pace: tick i (1..TICKS) goes out ROUND_TICK_MS * i after the band is laid */
export const ROUND_TICK_MS = 420;

export const EMOTES = ["wave", "tip-hat", "cheer", "shrug"] as const;
export type EmoteId = (typeof EMOTES)[number];

export const PHRASES = ["Hello", "Nice band", "Where are the fees?", "In range", "Out of range", "See you on the board", "Good game"] as const;
export type PhraseId = (typeof PHRASES)[number];

/** the hat-strap colours a visitor can pick (index 0 is Mr Bands' orange) */
export const STRAPS = ["#ff7a1a", "#1f7a4d", "#2f5d9e", "#b8321f", "#8a6a1c", "#6b3fa0"] as const;

export interface PlayerState {
  id: string;
  name: string;
  strap: number;
  x: number;
  z: number;
  /** heading, radians */
  ry: number;
  moving: boolean;
}

export interface ScoreRow {
  name: string;
  /** the pool the round was played on ("CARDS / USDC") */
  pool: string;
  /** the round's result against holding, percent of the deposit, two decimals */
  pct: number;
  at: number;
}

// ---------------------------------------------------------------- client -> server

export type C2S =
  | { t: "hello"; strap: number }
  | { t: "move"; x: number; z: number; ry: number; moving: boolean }
  | { t: "emote"; e: EmoteId }
  | { t: "say"; p: PhraseId }
  /**
   * lay a band on one of the live pools (by label or address; the server looks it up in its own copy of the board)
   * and start a round. One round open per player at a time, one lay a second.
   */
  | { t: "lay"; pool: string; widthBins: number; offsetBins: number }
  /** settle the open round now, at the last tick the server has sent (tick 1 if none has gone out yet) */
  | { t: "close"; roundId: string };

// ---------------------------------------------------------------- server -> client

export type S2C =
  | { t: "welcome"; you: string; name: string; players: PlayerState[]; board: ScoreRow[] }
  | { t: "join"; p: PlayerState }
  | { t: "leave"; id: string }
  /** batched positions: [id, x, z, ry, moving 0|1] */
  | { t: "moves"; m: [string, number, number, number, 0 | 1][] }
  | { t: "emote"; id: string; e: EmoteId }
  | { t: "say"; id: string; p: PhraseId }
  /** the band is down: the pool it was laid on (public board data), its price bounds relative to p0 = 1, the pace */
  | { t: "laid"; roundId: string; pool: import("./lpGame").PoolParams; lower: number; upper: number; tickMs: number }
  /** tick i (1..TICKS) of the server's round, sent when the server's clock reaches it; the SimResult arrays at i */
  | { t: "tick"; roundId: string; i: number; p: number; feesPct: number; valuePct: number; holdPct: number; inRange: boolean }
  /** the round is settled (closed, or it reached TICKS): pct against holding; rank on the board, or null if not on it */
  | { t: "scored"; roundId: string; pct: number; rank: number | null }
  | { t: "board"; rows: ScoreRow[] }
  | { t: "full" }
  /** the visitor is sending too much; messages are being dropped */
  | { t: "slow" }
  | { t: "error"; why: string };

export const isEmote = (v: unknown): v is EmoteId => typeof v === "string" && (EMOTES as readonly string[]).includes(v);
export const isPhrase = (v: unknown): v is PhraseId => typeof v === "string" && (PHRASES as readonly string[]).includes(v);
