/**
 * THE EXCHANGE'S WIRE FORMAT (bands.finance Play, 24 Sep). One contract for the browser (src/game/net.ts) and the
 * room server (game-server/, a Cloudflare Durable Object). JSON over one WebSocket per visitor.
 *
 * Safety by construction: no free text ever crosses the wire. A visitor's name is generated by the server, what
 * they say is one of PHRASES, what they do is one of EMOTES, and a leaderboard score is the server's own: an online
 * round is played on the server. The player lays a band ("lay"), the server deals a seed it never sends, runs
 * simulate() (src/game/lpGame.ts) and streams the result one tick at a time as its clock reaches each tick ("tick");
 * the player may "close" at any time, which settles the round at the last tick already sent. The browser never sees
 * the seed or any tick before its time, so there is nothing to search offline.
 *
 * THE STACK (24 Sep): every visitor keeps an account on the server, opened again by a key only their browser holds.
 * Its stack is in whole dollars (a band is $1,000). It grows at the stalls (a staked round pays back the stake plus
 * what the band made AGAINST JUST HOLDING: its fees less what it lost to holding, the same measure the board scores;
 * never the position's raw worth, which on a board of pools that just surged is a bet on a rise already known),
 * from Mr Bands (a daily wage and daily jobs, collected at his desk) and from loose notes found about the plaza.
 * Every change to a stack is the server's own.
 *
 * A STAKED ROUND IS COMMITTED AT THE LAY (24 Sep, after the review): width, centre, stake and the hours to ride
 * (`hold`) are all fixed before the server deals the hours, and the round settles at `hold` whatever happens after:
 * a "close" only skips to the end, a leave or a restart settles it there too. So nothing a player works out from the
 * ticks (the real hours are public data, and a stretch of them can be matched from its first tick) can change what a
 * staked round pays. A practice round (stake 0) may still be closed at any hour, and records nothing: no board row,
 * no job. The stall keeps RAKE_PCT of every stake, the game's one sink; a round's stake is at most MAX_STAKE, and a
 * round's fees at most FEES_CAP_PCT of the deposit (lpGame.ts); a band's value never beats holding, so what comes
 * back is at most 1.3 x the stake, and a stack grows a step at a time, never compounds.
 */

/** the plaza is a disc of this radius, in world units (metres); the server clamps every position into it */
export const WORLD_RADIUS = 42;
/** a client sends at most this many moves a second; the server drops the excess */
export const MOVE_HZ = 12;
/** the server broadcasts positions this many times a second, batched */
export const TICK_HZ = 10;
/** the most visitors one room holds; the next one gets { t: "full" } */
export const ROOM_CAP = 60;
/** the fastest a walker may move, metres a second (sprint included), for the server's sanity check */
export const MAX_SPEED = 9;
/** an online round's pace: tick i (1..TICKS) goes out ROUND_TICK_MS * i after the band is laid */
export const ROUND_TICK_MS = 420;

export const EMOTES = ["wave", "tip-hat", "cheer", "shrug"] as const;
export type EmoteId = (typeof EMOTES)[number];

export const PHRASES = ["Hello", "Nice band", "Where are the fees?", "In range", "Out of range", "See you on the board", "Good game"] as const;
export type PhraseId = (typeof PHRASES)[number];

/** the hat-strap colours a visitor can pick (index 0 is Mr Bands' orange) */
export const STRAPS = ["#ff7a1a", "#1f7a4d", "#2f5d9e", "#b8321f", "#8a6a1c", "#6b3fa0"] as const;

export interface PlayerState {
  id: string;
  name: string;
  strap: number;
  x: number;
  z: number;
  /** heading, radians */
  ry: number;
  moving: boolean;
  /** their stack, dollars */
  stack: number;
}

// ---------------------------------------------------------------- the stack

/** a band: a strapped stack of $1,000 */
export const BAND = 1000;
/** a new account's stack */
export const START_STACK = 1000;
/** the least a staked round takes (0 is a practice round: nothing staked, nothing won) */
export const MIN_STAKE = 100;
/** the most a staked round takes: one band, so a stack grows a step at a time */
export const MAX_STAKE = BAND;
/** the stall keeps this much of every stake at the lay (whole dollars, rounded up): the cost of laying, and the sink */
export const RAKE_PCT = 2;
/** the hours a staked round may commit to riding */
export const HOLDS = [12, 24, 48] as const;
/** staked rounds a day (UTC); practice rounds are unlimited */
export const ROUNDS_PER_DAY = 24;
/** Mr Bands' daily wage, collected at his desk */
export const WAGE = 250;
/** loose notes a player can pick up in a day */
export const NOTES_PER_DAY = 40;
/** how near a note you must be to pick it up, metres (the server's check) */
export const NOTE_REACH = 2;
/** where Mr Bands' pay is collected: the front of his desk, and how near it you must stand */
export const DESK_SPOT = { x: -20.9, z: 2.8, r: 4.5 } as const;

export type JobId = "range" | "beat" | "notes" | "wave";
/** Mr Bands' daily jobs: `need` of something in a day, paid `reward` once at his desk */
export const JOBS: readonly { id: JobId; need: number; reward: number }[] = [
  /** keep price inside your band 24 hours of one round */
  { id: "range", need: 24, reward: 300 },
  /** close a band ahead of just holding */
  { id: "beat", need: 1, reward: 300 },
  /** pick up 5 loose notes */
  { id: "notes", need: 5, reward: 200 },
  /** wave at someone standing near you */
  { id: "wave", need: 1, reward: 100 },
];

/** a player's own account, as they see it */
export interface Me {
  stack: number;
  /** in play on an open round (not in the stack until it settles) */
  staked: number;
  /** the UTC day the counts below are for, "2026-09-24" */
  day: string;
  wagePaid: boolean;
  jobs: { id: JobId; have: number; paid: boolean }[];
  /** staked rounds played today */
  rounds: number;
  /** notes picked up today */
  notes: number;
}

/** a loose note on the ground, worth v dollars */
export interface Note {
  id: string;
  x: number;
  z: number;
  v: number;
}

export interface StackRow {
  name: string;
  stack: number;
}

export interface ScoreRow {
  name: string;
  /** the pool the round was played on ("CARDS / USDC") */
  pool: string;
  /** the round's result against holding, percent of the deposit, two decimals */
  pct: number;
  at: number;
}

// ---------------------------------------------------------------- client -> server

export type C2S =
  /** key: the account key this browser was given, to open the same account again */
  | { t: "hello"; strap: number; key?: string }
  | { t: "move"; x: number; z: number; ry: number; moving: boolean }
  | { t: "emote"; e: EmoteId }
  | { t: "say"; p: PhraseId }
  /**
   * lay a band on one of the live pools (by address, or label; the server looks it up in its own copy of the board)
   * and start a round. One round open per player at a time, one lay a second. stake: dollars from the stack (absent or
   * 0: practice), MIN_STAKE..MAX_STAKE; hold: the hours a staked round rides, one of HOLDS (default 48; ignored for
   * practice).
   */
  | { t: "lay"; pool: string; widthBins: number; offsetBins: number; stake?: number; hold?: number }
  /** pick up a loose note (the server checks you stand within NOTE_REACH of it) */
  | { t: "pick"; note: string }
  /** collect the wage and any finished jobs (the server checks you stand at the desk) */
  | { t: "pay" }
  /**
   * a practice round: settle now, at the last tick the server has sent (tick 1 if none has gone out yet).
   * a staked round: skip to the end (the remaining ticks come at once and it settles at its hold)
   */
  | { t: "close"; roundId: string };

// ---------------------------------------------------------------- server -> client

export type S2C =
  /** key: sent once, when the account is new; the browser keeps it to come back to the same stack */
  | { t: "welcome"; you: string; name: string; players: PlayerState[]; board: ScoreRow[]; me: Me; notes: Note[]; stacks: StackRow[]; key?: string }
  /** this player's account changed */
  | { t: "me"; me: Me }
  /** someone's stack changed (for their name tag) */
  | { t: "stack"; id: string; stack: number }
  | { t: "notes"; add: Note[]; gone: string[] }
  /** someone picked up a note worth v */
  | { t: "picked"; id: string; note: string; v: number }
  /** Mr Bands paid this player: the wage and jobs collected, in dollars */
  | { t: "paid"; amount: number }
  /** the biggest stacks changed */
  | { t: "stacks"; rows: StackRow[] }
  /** this account was opened in another tab; this socket is closed */
  | { t: "elsewhere" }
  | { t: "join"; p: PlayerState }
  | { t: "leave"; id: string }
  /** batched positions: [id, x, z, ry, moving 0|1] */
  | { t: "moves"; m: [string, number, number, number, 0 | 1][] }
  | { t: "emote"; id: string; e: EmoteId }
  | { t: "say"; id: string; p: PhraseId }
  /**
   * the band is down: the pool it was laid on (public board data), its price bounds relative to p0 = 1, the pace,
   * whether the hours are a real stretch of the pool's history (which one is kept back until the round is scored),
   * and for a staked round the stake taken, the stall's cut and the hour it settles at
   */
  | { t: "laid"; roundId: string; pool: import("./lpGame").PoolParams; lower: number; upper: number; tickMs: number; real?: boolean; stake?: number; rake?: number; hold?: number }
  /** tick i (1..TICKS) of the server's round, sent when the server's clock reaches it; the SimResult arrays at i */
  | { t: "tick"; roundId: string; i: number; p: number; feesPct: number; valuePct: number; holdPct: number; inRange: boolean }
  /**
   * the round is settled (closed, skipped, or it reached its hold): pct against holding at the hour it settled (`at`);
   * rank on the Best rounds board (staked rounds only), or null; for a real round, when its stretch of history began
   * (unix seconds); for a staked round, the stake and what came back to the stack (the stake plus its result against
   * holding, never below 0)
   */
  | { t: "scored"; roundId: string; pct: number; at: number; rank: number | null; from?: number; stake?: number; back?: number }
  | { t: "board"; rows: ScoreRow[] }
  | { t: "full" }
  /** the visitor is sending too much; messages are being dropped */
  | { t: "slow" }
  | { t: "error"; why: string };

export const isEmote = (v: unknown): v is EmoteId => typeof v === "string" && (EMOTES as readonly string[]).includes(v);
export const isPhrase = (v: unknown): v is PhraseId => typeof v === "string" && (PHRASES as readonly string[]).includes(v);
